env: "local" #local, dev, prod
storage:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "postgres"
  db: "postgres"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "my_user"
  password: "my_pass"
