env: "local" #local, dev, prod
storage:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  db: "postgres"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "my_user"
  password: "my_pass"
stan:
  url: "http://stan:4222"
  cluster_id: "L0_cluster"
  client_id: "L0_sub"
  user_creds: ""
  channel: "L0_chan"